//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 9/19/2023 8:35:18 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace MVC_Template.Models
{
    public partial class ManufacturerOrderDetail
    {

        public ManufacturerOrderDetail()
        {
            OnCreated();
        }

        public int OrderDetailsID { get; set; }

        public int ManufOrderID { get; set; }

        public int ShipperID { get; set; }

        public string? TrackingInfo { get; set; }

        public int ProductID { get; set; }

        public decimal UnitPrice { get; set; }

        public int ProductQTY { get; set; }

        public decimal ShipperCost { get; set; }

        public decimal OrderTotal { get; set; }

        public DateTime TimeCreated { get; set; }

        public DateTime LastModified { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
