//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 9/19/2023 8:35:18 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace MVC_Template.Models
{
    public partial class Product
    {

        public Product()
        {
            OnCreated();
        }

        public int ProductID { get; set; }

        public string ProductName { get; set; }

        public string? ProductDescr { get; set; }

        public int? CategoryID { get; set; }

        public decimal Unitprice { get; set; }

        public bool? Discontinued { get; set; }

        public int? DiscountAmount { get; set; }

        public int ManufacturerOrderID { get; set; }

        public int? ProductWeight { get; set; }

        public int ShipperID { get; set; }

        public DateTime TimeCreated { get; set; }

        public DateTime LastModified { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
