//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 9/19/2023 8:35:18 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace MVC_Template.Models
{
    public partial class ProductCategory
    {

        public ProductCategory()
        {
            OnCreated();
        }

        public int CategoryID { get; set; }

        public string CategoryName { get; set; }

        public string? CategoryDescr { get; set; }

        public DateTime TimeCreated { get; set; }

        public DateTime LastModified { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
